services:
  app:
    container_name: recipe-app
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements/prod.txt
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
