# Generated by Django 5.1.2 on 2024-11-14 15:47

import apps.recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.recipe.models.recipe_image_file_path),
        ),
    ]
